name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      #- main
      - dev # FOR TESTING

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' 

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: List output files
      run: ls -R dist/  # Print out the files in the build directory to ensure the build was successful

    - name: Create .nojekyll file
      run: touch dist/.nojekyll  # Create a .nojekyll file to prevent GitHub Pages from ignoring files starting with an underscore

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .
        name: github-pages
        retention-days: 1

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: /home/runner/work/_temp/artifact.tar
        retention-days: 1
        if-no-files-found: error
        compression-level: 6
        overwrite: true
        include-hidden-files: false

  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
          preview: false