name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main
      #- dev # FOR TESTING

permissions: 
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' 

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # This will run both the CSS build and the Vite build

    - name: List output files
      run: ls -R dist/  # Print out the files in the build directory to ensure the build was successful

    - name: Create .nojekyll file
      run: touch dist/.nojekyll  # Create a .nojekyll file to prevent GitHub Pages from ignoring files starting with an underscore

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: dist
        name: github-pages
        retention-days: 1

  deploy: 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
          preview: false