name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - dev # TEMPORARILY RUN ON DEV BRANCH WHILE WORKING OUT THE KINKS

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build  # This will run both the CSS build and the Vite build

    - name: List output files
      run: ls -R build/  # Print out the files in the build directory to ensure the build was successful

    - name: Create .nojekyll file
      run: touch build/.nojekyll  # Create a .nojekyll file to prevent GitHub Pages from ignoring files starting with an underscore

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Ensure this matches your Vite build output directory